# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-helm-release
  description: Create helm release and common aws resources like an eks iam role
  homepage: https://cloudposse.com/accelerate
  topics: ""

